/* Índice de seções do Manual do Atendente ZapERP */
export const SECTIONS = [
  { id: "objetivo",           label: "Objetivo do ZapERP",        icon: "🎯", group: "Início" },
  { id: "acesso",             label: "Acesso ao Sistema",         icon: "🔐", group: "Início" },
  { id: "tela-principal",     label: "Tela Principal",            icon: "🖥️", group: "Início" },
  { id: "lista-conversas",    label: "Lista de Conversas",        icon: "💬", group: "Atendimento" },
  { id: "filtros",            label: "Filtros de Atendimento",    icon: "🔍", group: "Atendimento" },
  { id: "busca",              label: "Busca de Conversas",        icon: "🔎", group: "Atendimento" },
  { id: "status",             label: "Status dos Atendimentos",   icon: "🟢", group: "Atendimento" },
  { id: "assumir",            label: "Assumir Atendimento",       icon: "✅", group: "Atendimento" },
  { id: "compartilhado",      label: "Atendimento Compartilhado",  icon: "👥", group: "Atendimento" },
  { id: "responder",          label: "Responder Mensagens",       icon: "✍️", group: "Atendimento" },
  { id: "ordem-mensagens",    label: "Ordem das Mensagens",       icon: "📋", group: "Atendimento" },
  { id: "tempo-real",         label: "Tempo Real",                icon: "⚡", group: "Atendimento" },
  { id: "anexos",             label: "Anexos e Mídias",           icon: "📎", group: "Atendimento" },
  { id: "respostas-rapidas",  label: "Respostas Rápidas",         icon: "⚡", group: "Atendimento" },
  { id: "tags",               label: "Tags e Identificações",     icon: "🏷️", group: "Organização" },
  { id: "setores",            label: "Setores e Departamentos",   icon: "🏢", group: "Organização" },
  { id: "transferir",         label: "Transferir Atendimento",    icon: "↔️", group: "Organização" },
  { id: "grupos",             label: "Grupos de WhatsApp",        icon: "👥", group: "Organização" },
  { id: "pendencias",         label: "Minhas Pendências",         icon: "📋", group: "Organização" },
  { id: "historico",          label: "Histórico da Conversa",     icon: "📜", group: "Organização" },
  { id: "dados-cliente",      label: "Dados do Cliente",          icon: "👤", group: "Organização" },
  { id: "observacoes",        label: "Observações Internas",      icon: "📝", group: "Organização" },
  { id: "finalizar",          label: "Finalizar Atendimento",     icon: "✖️", group: "Finalização" },
  { id: "protocolo",          label: "Protocolo",                 icon: "🔢", group: "Finalização" },
  { id: "avaliacao",          label: "Avaliação",                 icon: "⭐", group: "Finalização" },
  { id: "reabrir",            label: "Reabrir Atendimento",       icon: "🔄", group: "Finalização" },
  { id: "financeiro",         label: "Atendimento Financeiro",    icon: "💰", group: "Por Tipo" },
  { id: "suporte",            label: "Atendimento de Suporte",    icon: "🔧", group: "Por Tipo" },
  { id: "comercial",          label: "Atendimento Comercial",     icon: "💼", group: "Por Tipo" },
  { id: "por-setor",          label: "Atendimento por Setor",     icon: "🏗️", group: "Por Tipo" },
  { id: "chatbot",            label: "Chatbot e Triagem",         icon: "🤖", group: "Avançado" },
  { id: "administrador",      label: "Controle do Administrador", icon: "👁️", group: "Avançado" },
  { id: "boas-praticas",      label: "Boas Práticas",             icon: "✨", group: "Avançado" },
  { id: "nao-fazer",          label: "O que Não Fazer",           icon: "🚫", group: "Avançado" },
  { id: "prioridade",         label: "Prioridade de Atendimento", icon: "🔥", group: "Avançado" },
  { id: "pedir-ajuda",        label: "Quando Pedir Ajuda",        icon: "🆘", group: "Avançado" },
  { id: "conferencia",        label: "Conferência Antes de Finalizar", icon: "✔️", group: "Avançado" },
  { id: "problemas",          label: "Problemas Comuns",          icon: "❓", group: "Avançado" },
  { id: "producao",           label: "Regras para Produção",      icon: "🏭", group: "Avançado" },
  { id: "fluxo-ideal",        label: "Fluxo Ideal",               icon: "🔄", group: "Referência" },
  { id: "checklist",          label: "Checklist do Atendente",    icon: "☑️", group: "Referência" },
];

export const GROUPS = [
  "Início",
  "Atendimento",
  "Organização",
  "Finalização",
  "Por Tipo",
  "Avançado",
  "Referência",
];
